# Generated by Django 6.0.4 on 2026-04-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_favorite',
        ),
    ]
